version: '3.4'

services:
  projectservice:
    image: ${DOCKER_REGISTRY-}projectservice
    build:
      context: .
      dockerfile: ProjectService\Dockerfile

  teamservice:
    image: ${DOCKER_REGISTRY-}teamservice
    build:
      context: .
      dockerfile: TeamService\Dockerfile

